spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      data: 0
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB
  batch:
    jdbc:
      initialize-schema: always

secret:
  at: ${AT_SECRET}
  rt: ${RT_SECRET}

expiration:
  at: ${AT_EXP}
  rt: ${RT_EXP}

guest:
  uuid: ${GUEST_UUID}
  profile: ${GUEST_PROFILE}

cloud:
  aws:
    s3:
      bucketName: ${S3_BUCKETNAME}
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      domain: ${CLOUDFRONT_DOMAIN}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true
  paths-to-match:
    - /api/**